# Generated by Django 5.0.1 on 2024-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=10000)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
